# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170505_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default=b'body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=b'title', max_length=50),
        ),
    ]
