# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 07:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170506_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 6, 7, 6, 7, 602786, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=b'title', unique=True),
        ),
    ]
